import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/skills'
import Project from '../components/Project'
import Contact from '../components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        <title>Tahasin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Main/>
      <About/>
      <Skills/>
      <Project/>
      <Contact/>
    </>
  )
}
